# Generated by Django 6.0.2 on 2026-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeSlug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagSlug',
            new_name='slug',
        ),
    ]
