# Generated by Django 6.0.2 on 2026-02-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=20)),
                ('postText', models.TextField()),
                ('publication_Date', models.DateField(auto_now_add=True, unique_for_month='publication_Date')),
                ('postSlug', models.SlugField(max_length=30, unique=True)),
                ('recipes', models.ManyToManyField(related_name='blog_posts', to='organiser.recipe')),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='organiser.tag')),
            ],
        ),
    ]
