# Generated by Django 6.0.2 on 2026-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='postSlug',
            new_name='slug',
        ),
    ]
